namespace inter_sdk_library;
    public static class Constants
    {
        public const string DOC_CERTIFICATE = "https://developers.bancointer.com.br/v4/docs/onde-obter-o-certificado";
        public const string URL_BANKING = "/banking/v2";
        public const string URL_BANKING_BALANCE = URL_BANKING + "/saldo";
        public const string URL_TOKEN = "/oauth/v2/token";
        public const string URL_BANKING_STATEMENT = URL_BANKING + "/extrato";
        public const string URL_BANKING_ENRICHED_STATEMENT = URL_BANKING_STATEMENT + "/completo";
        public const string URL_BANKING_STATEMENT_PDF = URL_BANKING_STATEMENT + "/exportar";
        public const string URL_BANKING_PAYMENT = URL_BANKING + "/pagamento";
        public const string URL_BANKING_PAYMENT_DARF = URL_BANKING_PAYMENT + "/darf";
        public const string URL_BANKING_PAYMENT_BATCH = URL_BANKING_PAYMENT + "/lote";
        public const string URL_BANKING_PAYMENT_PIX = URL_BANKING + "/pix";
        public const string URL_BANKING_WEBHOOK = URL_BANKING + "/webhooks";
        public const string URL_PIX = "/pix/v2";
        public const string URL_PIX_PIX = URL_PIX + "/pix";
        public const string URL_PIX_LOCATIONS = URL_PIX + "/loc";
        public const string URL_PIX_IMMEDIATE_BILLINGS = URL_PIX + "/cob";
        public const string URL_PIX_SCHEDULED_BILLINGS = URL_PIX + "/cobv";
        public const string URL_PIX_SCHEDULED_BILLINGS_BATCH = URL_PIX + "/lotecobv";
        public const string URL_PIX_WEBHOOK = URL_PIX + "/webhook";
        public const string URL_PIX_WEBHOOK_CALLBACKS = URL_PIX_WEBHOOK + "/callbacks";
        public const string URL_BILLING = "/cobranca/v3/cobrancas";
        public const string URL_BILLING_SUMMARY = URL_BILLING + "/sumario";
        public const string URL_BILLING_WEBHOOK = URL_BILLING + "/webhook";
        public const string URL_BILLING_WEBHOOK_CALLBACKS = URL_BILLING_WEBHOOK + "/callbacks";
        public const string BILLET_BILLING_READ_SCOPE = "boleto-cobranca.read";
        public const string BILLET_BILLING_WRITE_SCOPE = "boleto-cobranca.write";
        public const string READ_BALANCE_SCOPE = "extrato.read";
        public const string BILLET_PAYMENT_READ_SCOPE = "pagamento-boleto.read";
        public const string BILLET_PAYMENT_WRITE_SCOPE = "pagamento-boleto.write";
        public const string DARF_PAYMENT_WRITE_SCOPE = "pagamento-darf.write";
        public const string BATCH_PAYMENT_READ_SCOPE = "pagamento-lote.read";
        public const string BATCH_PAYMENT_WRITE_SCOPE = "pagamento-lote.write";
        public const string PIX_PAYMENT_WRITE_SCOPE = "pagamento-pix.write";
        public const string PIX_PAYMENT_READ_SCOPE = "pagamento-pix.read";
        public const string WEBHOOK_BANKING_READ_SCOPE = "webhook-banking.read";
        public const string WEBHOOK_BANKING_WRITE_SCOPE = "webhook-banking.write";
        public const string PIX_IMMEDIATE_BILLING_READ_SCOPE = "cob.read";
        public const string PIX_IMMEDIATE_BILLING_WRITE_SCOPE = "cob.write";
        public const string PIX_SCHEDULED_BILLING_READ_SCOPE = "cobv.read";
        public const string PIX_SCHEDULED_BILLING_WRITE_SCOPE = "cobv.write";
        public const string PIX_SCHEDULED_BILLING_BATCH_WRITE_SCOPE = "lotecobv.write";
        public const string PIX_SCHEDULED_BILLING_BATCH_READ_SCOPE = "lotecobv.read";
        public const string PIX_READ_SCOPE = "pix.read";
        public const string PIX_WRITE_SCOPE = "pix.write";
        public const string PIX_LOCATION_READ_SCOPE = "payloadlocation.read";
        public const string PIX_LOCATION_WRITE_SCOPE = "payloadlocation.write";
        public const string PIX_WEBHOOK_READ_SCOPE = "webhook.read";
        public const string PIX_WEBHOOK_WRITE_SCOPE = "webhook.write";
        public const int DAYS_TO_EXPIRE = 30;
        public const string CERTIFICATE_EXCEPTION_MESSAGE = "Certificate error!";
        public const string GENERIC_EXCEPTION_MESSAGE = "Error executing SDK!";
    }

